account/urls.py
from django.conf.urls import url

from views import *

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^auth/', include('account.urls', namespace='account')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^', include('export.urls', namespace='export')),
]

templates/page/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %} СМУС - демо {% endblock %}</title>
  {% load pipeline %}
  {% javascript 'bower' %}
  {% javascript 'custom' %}
  {% stylesheet 'bower' %}
  {% stylesheet 'custom' %}
</head>
<body>
  <div class="wrapper">
    <header role="header">
      <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'home' %}">
              Система мониторинга успеваемости студентов
            </a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            {% block nav %}
              <ul class="nav navbar-nav">
                <li><a href="{% url 'speciality' 'bachelor' %}">Бакалавриат</a></li>
                <li><a href="{% url 'speciality' 'magister' %}">Магистратура</a></li>
              </ul>
            {% endblock %}
            <!-- <ul class="nav navbar-nav navbar-right">
              <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Поиск">
                </div>
                <button type="submit" class="btn btn-default">Поиск</button>
              </form>
            </ul> -->
            <ul class="nav navbar-nav navbar-right">
              <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Поиск">
                </div>
                <button type="submit" class="btn btn-default">Поиск</button>
              </form>
            </ul>
            {% block auth %}
              <div class="nav navbar-nav navbar-right login-bar">
                <span class="navbar-text">
                  Вы вошли как
                </span>
                <div class="dropdown navbar-text">
                  <a href="#" class="navbar-link" type="button" id="dropdown-logout" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    {{ request.user.username }}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenu-logout">
                    <li><a href="{% url 'account:logout' %}">Выйти</a></li>
                  </ul>
                </div>
                <span class="navbar-text">
                  <i class="glyphicon glyphicon-user"></i>
                </span>
              </div>
            {% endblock %}
          </div>
        </div>
      </nav>
    </header>
    {% block breadcrumbs %}
    {% endblock %}
    <div class="messages">
      <div class="container">
        {% block messages %}
        {% endblock %}
      </div>
    </div>
    <article role="content">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            {% block content %}
              <h1>Hello world!</h1>
            {% endblock %}
          </div>
        </div>
      </div>
    </article>
  </div>
  <footer class="footer" role="footer">
    <div class="container">
      <a href="mailto:ravbetsky@ulsu.ru" class="pull-right">ravbetsky@ulsu.ru</a>
      <p class="text-muted pull-left">Система мониторинга успеваемости и посещаемости студентов. УлГУ, Кафедра "ММТС", 2016 г.</p>
    </div>
  </footer>
</body>
</html>