app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^auth/', include('account.urls', namespace='account')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^', include('export.urls', namespace='export')),
]

core/urls.py
from django.conf.urls import url
from views import GroupView, SpecialityView, StaffView, StudentView

urlpatterns = [
    url(r'^group/(?P<pk>\d+)/$', GroupView.as_view(), name='group'),
    url(r'^staff/(?P<pk>\d+)/$', StaffView.as_view(), name='staff'),
    url(r'^student/(?P<pk>\d+)/$', StudentView.as_view(), name='student'),
    # url(r'^search/$', GroupView.as_view(), name='search'),
    # url(r'^bachelor/$', GroupView.as_view(), name='speciality', {'level': 'bachelor',})
    # url(r'^magister/$', GroupView.as_view(), name='speciality', {'level': 'magister',})
    url(r'^(?P<level>bachelor|magister)/$', SpecialityView.as_view(), name='speciality')
]

attendance/models.py
# -*- coding:utf-8 -*-
from django.db import models

from core.models import SemesterSubject, Student, StudentGroup


class Attendance(models.Model):
    student = models.ForeignKey(Student, verbose_name=u'студент')
    attended = models.BooleanField(u'присутствовал', default=False)
    lesson = models.ForeignKey('Lesson', verbose_name=u'занятие')

    def __unicode__(self):
        return u'%s, %s, %s' % (self.student, self.lesson.semester_subject, self.lesson.date)

    class Meta:
        verbose_name = u'посещение'
        verbose_name_plural = u'посещения'


class Lesson(models.Model):
    semester_subject = models.ForeignKey(SemesterSubject, verbose_name=u'предмет', related_name='lessons')
    date = models.DateField(verbose_name=u'дата')

    def __unicode__(self):
        return u'%s, %s' % (self.semester_subject, self.date)

    def save(self, *args, **kwargs):
        super(Lesson, self).save(*args, **kwargs)
        for student in self.semester_subject.semester.group.students.all():
            Attendance.objects.get_or_create(
                student=student,
                lesson=self
            )

    class Meta:
        verbose_name = u'занятие'
        verbose_name_plural = u'занятия'

thesis/models.py
# -*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from core.models import Semester, Student, Staff


class Thesis(models.Model):
    semester = models.ForeignKey(Semester, verbose_name=u'семестр')
    student = models.ForeignKey(Student, verbose_name=u'студент')
    topic = models.TextField(u'тема', blank=True, default='')
    progress = models.PositiveIntegerField(u'прогресс', default=0)
    professor = models.ForeignKey(Staff, verbose_name=u'научный руководитель', null=True, blank=True)
    last_change_date = models.DateField(u'дата последнего изменения', null=True, blank=True)

    def __unicode__(self):
        return '%s, %s' % (self.semester, self.student)

    class Meta:
        verbose_name = u'работа'
        verbose_name_plural = u'курсовые и дипломы'

attendance/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render
from django.template.defaultfilters import date

from models import Attendance


class AttendanceMixin(object):
    def get_attendance_data(self, semester, subject, dates):
        if semester is None:
            semester = self.object.current_semester
            if semester is None:
                return []

        data = {}
        students = self.object.students.all()
        if subject is None:
            subjects = self.object.get_subjects(semester)
        else:
            subjects = self.object.get_subjects(semester, [subject])
        students_data = []
        for student in students:
            subjects_data = []
            attendance_all_subjects = 0
            for subject in subjects:
                attendance = []

                dates_query = {}
                if dates[0]:
                    dates_query['date__gte'] = dates[0]
                if dates[1]:
                    dates_query['date__lte'] = dates[1]
                lessons = subject.lessons.filter(**dates_query)
                attendance_count = 0
                for lesson in lessons:
                    a, created = Attendance.objects.get_or_create(
                        lesson=lesson,
                        student=student
                    )
                    attendance.append({
                        'lesson': lesson,
                        'attended': a.attended
                    })
                    if a.attended:
                        attendance_count += 1

                attendance_value = int(attendance_count*100.0/lessons.count()) if lessons.count() else 0
                subjects_data.append({
                    'subject': subject,
                    'attendance': attendance,
                    'attendance_overall': attendance_value,
                })
                attendance_all_subjects += attendance_value
            students_data.append({
                'student': student,
                'subjects': subjects_data,
                'attendance_all_subjects': int(attendance_all_subjects/subjects.count()) if subjects.count() else 0
            })

        subjects_data_full = []
        for subject in subjects:
            if dates[0]:
                dates_query['date__gte'] = dates[0]
            if dates[1]:
                dates_query['date__lte'] = dates[1]
            lessons = subject.lessons.filter(**dates_query)
            subjects_data_full.append({
                'subject': subject,
                'lessons': lessons
            })

        data['students'] = students_data
        data['subjects'] = subjects_data_full
        return data

    def write_xls(self, workbook):
        ws = workbook.add_sheet(u'Посещаемость группы')
        attendance_data = self.get_attendance_data(self.semester, self.subject, self.dates)

        ws.write_merge(0, 1, 0, 0, u'ФИО студента/ Дисциплина')
        ws.write_merge(0, 1, 1, 1, u'%')
        ws.col(0).width = 500 * 20
        ws.col(1).width = 50 * 20
        thead_i = 1
        for subject in attendance_data['subjects']:
            length = subject['lessons'].all().count()+1
            ws.write_merge(0, 0, thead_i+1, thead_i+length, subject['subject'].subject.name)

            thead_i_2 = thead_i+1
            for lesson in subject['lessons']:
                ws.write(1, thead_i_2, date(lesson.date, 'd.m.Y'))
                ws.col(thead_i_2).width = 200 * 20
                thead_i_2 += 1
            ws.write(1, thead_i_2, '%')
            ws.col(thead_i_2).width = 50 * 20

            thead_i += length

        students_i = 2
        for student in attendance_data['students']:
            ws.write(students_i, 0, '%s %s' % (student['student'].last_name, student['student'].first_name))
            ws.write(students_i, 1, student['attendance_all_subjects'])
            students_i_2 = 2
            for subject in student['subjects']:
                for lesson in subject['attendance']:
                    if not lesson['attended']:
                        ws.write(students_i, students_i_2, u'н')
                    students_i_2 += 1
                ws.write(students_i, students_i_2, subject['attendance_overall'])
                students_i_2 += 1
            students_i += 1
        return workbook

    def get_context_data(self, **kwargs):
        context = super(AttendanceMixin, self).get_context_data(**kwargs)
        context['attendance_data'] = self.get_attendance_data(self.semester, self.subject, self.dates)
        return context

core/views.py
# -*- coding:utf-8 -*-

from django.views.generic import DetailView, ListView
from django.http import Http404

from models import StudentGroup, Speciality, Staff, Student, Subject
from attendance.views import AttendanceMixin
from progress.views import ProgressMixin
from thesis.views import ThesisMixin


class StaffView(DetailView):
    model = Staff
    template_name = 'staff/view.html'


class StudentView(DetailView):
    model = Student
    template_name = 'student/view.html'


class MainMixin(object):
    semester = None
    subject = None
    dates = None

    def get_semester(self):
        semester_number = self.request.GET.get('semester', None)
        if semester_number is not None:
            semester_number = int(semester_number)
        semester = self.object.get_semester(semester_number)
        if semester is None:
            raise Http404
        return semester

    def get_subject(self):
        subject_id = self.request.GET.get('subject', None)
        subject = None
        if subject_id is not None:
            try:
                subject = Subject.objects.get(id=subject_id)
            except Subject.DoesNotExist:
                raise Http404
            if not self.semester.subjects.filter(subject=subject):
                raise Http404
        return subject

    def get_dates(self):
        lessons_from = self.request.GET.get('from_date', None)
        lessons_to = self.request.GET.get('to_date', None)
        return lessons_from, lessons_to

    def get_object(self, queryset=None):
        obj = super(MainMixin, self).get_object(queryset)
        self.object = obj
        self.group = obj
        self.semester = self.get_semester()
        self.subject = self.get_subject()
        self.dates = self.get_dates()
        return obj

    def get_context_data(self, **kwargs):
        context = super(MainMixin, self).get_context_data(**kwargs)
        print self.dates
        context['semesters_list'] = [
            {'semester': s,
             'number': s.number
             } for s in self.object.semesters.all()
        ]
        context['subjects_list'] = [
            {'name': s.subject.name,
             'id': s.subject.id
             } for s in self.semester.subjects.all()
            ]
        context['current_semester'] = self.semester
        context['current_subject'] = self.subject
        context['current_dates'] = self.dates
        return context


class GroupView(AttendanceMixin, ProgressMixin, ThesisMixin, MainMixin, DetailView):
    model = StudentGroup
    template_name = 'group/view.html'


class SpecialityView(ListView):
    model = Speciality
    template_name = 'speciality/view.html'

    def get_context_data(self, **kwargs):
        context = super(SpecialityView, self).get_context_data(**kwargs)
        context['speciality_type'] = u'Бакалавриат' if self.kwargs['level'] == 'bachelor' else u'Магистратура'
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = super(SpecialityView, self).get_queryset(*args, **kwargs)
        queryset = queryset.filter(speciality_type=self.kwargs['level'])
        return queryset

thesis/views.py
# -*- coding:utf-8 -*-
from django.http import Http404
from django.template.defaultfilters import date

from models import Thesis


class ThesisMixin(object):
    def write_xls(self, workbook):
        ws = workbook.add_sheet(u'Курсовые работы')
        thesis_data = self.semester.thesis_set.all()

        ws.write(0, 0, u'ФИО студента')
        ws.write(0, 1, u'Тема курсовой работы')
        ws.write(0, 2, u'Научный руководитель')
        ws.write(0, 3, u'Прогресс')
        ws.write(0, 4, u'Дата обновления')
        ws.write(0, 5, u'Оценка')

        students_i = 1
        for thesis in thesis_data:
            ws.write(students_i, 0, '%s %s' % (thesis.student.last_name, thesis.student.first_name))
            ws.write(students_i, 1, thesis.topic)
            ws.write(students_i, 2, thesis.professor.__unicode__() if thesis.professor else '')
            ws.write(students_i, 3, '%s%%' % thesis.progress)
            ws.write(students_i, 4, date(thesis.last_change_date, 'd.m.Y'))
            ws.write(students_i, 5, '')
            students_i += 1

        ws.col(0).width = 500 * 20
        ws.col(1).width = 600 * 20
        ws.col(2).width = 400 * 20
        ws.col(3).width = 200 * 20
        ws.col(4).width = 200 * 20
        ws.col(5).width = 200 * 20

        if self.group.get_final_semester:
            final_thesis_data = self.group.get_final_semester.thesis_set.all()
        else:
            final_thesis_data = None

        if final_thesis_data:
            ws = workbook.add_sheet(u'Дипломные работы')
            ws.write(0, 0, u'ФИО студента')
            ws.write(0, 1, u'Тема дипломной работы')
            ws.write(0, 2, u'Научный руководитель')
            ws.write(0, 3, u'Прогресс')
            ws.write(0, 4, u'Дата обновления')
            ws.write(0, 5, u'Оценка')

            students_i = 1
            for thesis in final_thesis_data:
                ws.write(students_i, 0, '%s %s' % (thesis.student.last_name, thesis.student.first_name))
                ws.write(students_i, 1, thesis.topic)
                ws.write(students_i, 2, thesis.professor.__unicode__() if thesis.professor else '')
                ws.write(students_i, 3, '%s%%' % thesis.progress)
                ws.write(students_i, 4, date(thesis.last_change_date, 'd.m.Y'))
                ws.write(students_i, 5, '')
                students_i += 1

            ws.col(0).width = 500 * 20
            ws.col(1).width = 600 * 20
            ws.col(2).width = 400 * 20
            ws.col(3).width = 200 * 20
            ws.col(4).width = 200 * 20
            ws.col(5).width = 200 * 20
        return workbook

    def get_context_data(self, **kwargs):
        context = super(ThesisMixin, self).get_context_data(**kwargs)
        if not self.semester.is_final:
            context['thesis_data'] = self.semester.thesis_set.all()
        else:
            raise Http404

        if self.group.get_final_semester:
            context['final_thesis_data'] = self.group.get_final_semester.thesis_set.all()
        else:
            context['final_thesis_data'] = None

        return context

core/templates/group/attendance.html
<div class="content-attendance">
  <div class="top-controls">
    <div class="row">
      <div class="col-md-1">
        <button class="btn btn-default" onclick="window.attendanceTable.refreshTable()"><i class="glyphicon glyphicon-refresh"></i> Сбросить</button>
      </div>
      <div class="col-md-2">
        <form>
          <div class="checkbox">
            <label>
              <input type="checkbox" onclick="window.attendanceTable.showOnlyPercents(this)" checked> % по всем дисцплинам
            </label>
          </div>
        </form>
      </div>
      <div class="col-md-6">
        <div class="filter-by">
          <form class="form-inline">
            <div class="form-group">
              <label>Семестр</label>
              <select class="selectpicker" name="semester" onchange="window.attendanceTable.filterBySemester(this)">
                  {% for semester in semesters_list %}
                    <option value="{{ semester.number }}" {% if current_semester.number == semester.number %} selected="selected"{% endif %}>
                        {{ semester.number }} семестр
                    </option>
                  {% endfor %}
              </select>
            </div>
            <div class="form-group subject-select">
              <label for="subject">Предмет</label>
              <select class="selectpicker" name="subject" onchange="window.attendanceTable.filterBySubject(this)">
                <option value="all">Все предметы</option>
                {% for subject in subjects_list %}
                  <option value="{{ subject.id }}"{% if current_subject.id == subject.id %} selected="selected"{% endif %}>{{ subject.name }}</option>
                {% endfor %}
              </select>
            </div>
          </form>
        </div>
      </div>
      <div class="col-md-3">
        <div class="date-by">
          <form class="form-inline">
            <div class="form-group">
              <div class="input-group date" data-provide="datepicker">
                  <input type="text" name="from_date" id="from_date" class="form-control" placeholder="C" onchange="window.attendanceTable.filterByDate(this)" data-start-value="{% if current_dates.0 %}{{ current_dates.0 }}{% endif %}">
                  <div class="input-group-addon">
                      <span class="glyphicon glyphicon-th"></span>
                  </div>
              </div>
            </div>
            <span class="divider">-</span>
            <div class="form-group">
                <div class="input-group date" data-provide="datepicker">
                    <input type="text" name="to_date" id="to_date" class="form-control" placeholder="По" onchange="window.attendanceTable.filterByDate(this)" data-form-value="{% if current_dates.1 %}{{ current_dates.1 }}{% endif %}">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-th"></span>
                    </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  <div class="main-table">
    <table data-toggle="table" id="attendance_table" data-fixed-columns="true" data-fixed-number="1" data-sort-name="attendance">
      <thead>
        <tr>
            <th class="student_name" rowspan="2">ФИО студента/ Дисциплина</th>
            <th class="attendance_overall"  data-field="attendance_all_subjects" rowspan="2" data-field="student_{{ student.student.id }}_attendance_all" data-sortable="true">
              %
            </th>
            {% for subject in attendance_data.subjects %}

              <th class="subject" data-field="subject_{{ subject.subject.id }}" colspan="{{ subject.lessons.all|length|add:'1' }}">{{ subject.subject.subject.name }}</th>
            {% endfor %}
        </tr>
        <tr>

          {% for subject in attendance_data.subjects %}
            {% for lesson in subject.lessons %}
            <th class="attendance_date" data-field="attendance_fact_{{ forloop.counter }}_{{ subject.id }}">{{ lesson.date|date:"d.m.Y" }}</th>
            {% endfor %}
            <th data-sortable="true" data-field="attendance_all_{{ subject.id }}">%</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for student in attendance_data.students %}
          <tr>
            <td><span class="count">{{ forloop.counter }}. </span>
              <a href="{% url 'student' student.student.id %}">{{ student.student.last_name }} {{ student.student.first_name }}</a>
              <!-- {% if forloop.counter == 4 %}
                <i class="fa fa-star" aria-hidden="true"></i>
              {% endif %} -->
            </td>
            {% if student.attendance_all_subjects < 30 %}
              <td class="att-percent red">{{ student.attendance_all_subjects }}</td>
            {% else %}
              {% if student.attendance_all_subjects < 60 %}
                <td class="att-percent orange">{{ student.attendance_all_subjects }}</td>
              {% else %}
                {% if student.attendance_all_subjects < 75 %}
                  <td class="att-percent yellow">{{ student.attendance_all_subjects }}</td>
                {% else %}
                  <td class="att-percent green">{{ student.attendance_all_subjects }}</td>
                {% endif %}
              {% endif %}
            {% endif %}
            {% for subject in student.subjects %}
              {% for lesson in subject.attendance %}
              <td>
                {% if not lesson.attended %}
                  <span class='non'>н</span>
                {% endif %}
              </td>
              {% endfor %}
              <td class="att-percent">{{ subject.attendance_overall }}</td>
            {% endfor %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

core/templates/group/final_thesis.html
<div class="content-graduatework">
  <div class="top-controls">
    <div class="row">
      <div class="col-md-2">
        <button class="btn btn-default" onclick="window.graduateworkTable.refreshTable()"><i class="glyphicon glyphicon-refresh"></i> Сбросить</button>
      </div>
    </div>
  </div>
  <div class="main-table">
    <table data-toggle="table" data-sort-name="graduatework" id="graduatework_table">
      <thead>
        <tr>
          <th class='graduatework_student'>ФИО студента</th>
          <th class='graduatework_name'>Тема дипломной работы</th>
          <th class='graduatework_reviewer'>Научный руководитель</th>
          <th class='graduatework_progress' data-sortable="true" data-sorter="window.graduateworkTable.sortByProgress">Прогресс</th>
          <th class='graduatework_date'>Дата обновления</th>
          <th class='graduatework_grade' data-sortable="true">Оценка</th>
        </tr>
      </thead>
      <tbody>
        {% for thesis in final_thesis_data %}
        {% if thesis.topic %}
        <tr>
          <td class="student">
            <span class="count">{{ forloop.counter }}. </span>
            <a href="{% url 'student' thesis.student.id %}">{{ thesis.student.last_name }} {{ thesis.student.first_name }}</a>
            <!-- {% if forloop.counter == 4 %}
              <i class="fa fa-star" aria-hidden="true"></i>
            {% endif %} -->
          </td>
          <td>
            {{ thesis.topic }}
          </td>
          <td>
            {{ thesis.professor }}
          </td>
          <td>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="{{ thesis.progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ thesis.progress }}%;">
                {{ thesis.progress }}%
              </div>
            </div>
          </td>
          <td>
            <span>{{ thesis.last_change_date|date:'d.m.Y' }}</span>
          </td>
          <td>
            <span>&nbsp;</span>
          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

core/templates/group/progress.html
<div class="content-progress">
  <div class="top-controls">
    <div class="row">
      <div class="col-md-2">
        <button class="btn btn-default" onclick="window.progressTable.refreshTable()"><i class="glyphicon glyphicon-refresh"></i> Сбросить</button>
      </div>
      <div class="col-md-5">
        <div class="filter-by">
          <form class="form-inline">
            <div class="form-group">
              <label>Семестр</label>
              <select class="selectpicker" name="semester" onchange="window.progressTable.filterBySemester(this)">
                  {% for semester in semesters_list %}
                    <option value="{{ semester.number }}"
                            {% if current_semester.number == semester.number %} selected="selected"{% endif %}>
                        {{ semester.number }} семестр
                    </option>
                  {% endfor %}
              </select>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="main-table">
    <table data-toggle="table" data-sort-name="progress" data-sort-order="desc" id="progress_table">
      <thead>
        <tr>
          <th class='progress_student' rowspan="2">ФИО студента</th>
          <th class='progress_score' rowspan="2" data-sortable="true">Средний балл</th>
          <th class='progress_pass' colspan="{{ progress_data.subjects.exam|length }}">Зачеты</th>
          <th class='progress_examen' colspan="{{ progress_data.subjects.credit|length }}">Экзамены</th>
        </tr>
        <tr>
            {% for subject in progress_data.subjects.credit %}
                <th class="sunbject_progress">{{ subject.subject.name }}</th>
            {% empty %}
                <th class="sunbject_progress">&nbsp;</th>
            {% endfor %}
            {% for subject in progress_data.subjects.exam %}
                <th class="sunbject_progress">{{ subject.subject.name }}</th>
            {% empty %}
                <th class="sunbject_progress">&nbsp;</th>
            {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for student in progress_data.students %}
        <tr>
          <td class="student">
            <span class="count">{{ forloop.counter }}. </span>
            <a href="{% url 'student' student.student.id %}">{{ student.student.last_name }} {{ student.student.first_name }}</a>
            <!-- {% if forloop.counter == 4 %}
              <i class="fa fa-star" aria-hidden="true"></i>
            {% endif %} -->
          </td>
          <td class="progress_score">{{ student.progress_overall }}</td>
          {% if not progress_data.subjects.credit %}
            <td><span class="pass pass-ok">&nbsp;</span></td>
          {% endif %}
          {% for subject in student.subjects %}
            <td><span class="pass pass-ok">{{ subject.progress }}</span></td>
          {% endfor %}
          {% if not progress_data.subjects.exam %}
            <td><span class="pass pass-ok">&nbsp;</span></td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

core/templates/group/thesis.html
<div class="content-coursework">
  <div class="top-controls">
    <div class="row">
      <div class="col-md-2">
        <button class="btn btn-default" onclick="window.courseworkTable.refreshTable()"><i class="glyphicon glyphicon-refresh"></i> Сбросить</button>
      </div>
      <div class="col-md-8">
        <div class="filter-by">
          <form class="form-inline">
            <div class="form-group">
              <label>Семестр</label>
              <select class="selectpicker" name="semester" onchange="window.courseworkTable.filterBySemester(this)">
                  {% for semester in semesters_list %}
                      {% if not semester.is_final %}
                        <option value="{{ semester.number }}"
                          {% if current_semester.number == semester.number %} selected="selected"{% endif %}>
                          {{ semester.number }} семестр
                        </option>
                      {% endif %}
                  {% endfor %}
              </select>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="main-table">
    <table data-toggle="table" data-sort-name="coursework" id="coursework_table">
      <thead>
        <tr>
          <th class='coursework_student'>ФИО студента</th>
          <th class='coursework_name'>Тема курсовой работы</th>
          <th class='coursework_reviewer'>Научный руководитель</th>
          <th class='coursework_progress' data-sortable="true" data-sorter="window.courseworkTable.sortByProgress">Прогресс</th>
          <th class='coursework_date'>Дата обновления</th>
          <th class='coursework_grade' data-sortable="true">Оценка</th>
        </tr>
      </thead>
      <tbody>
        {% for thesis in thesis_data %}
        {% if thesis.topic %}
        <tr>
          <td class="student">
            <span class="count">{{ forloop.counter }}. </span>
            <a href="{% url 'student' thesis.student.id %}">{{ thesis.student.last_name }} {{ thesis.student.first_name }}</a>
            <!-- {% if forloop.counter == 4 %}
              <i class="fa fa-star" aria-hidden="true"></i>
            {% endif %} -->
          </td>
          <td>
            {{ thesis.topic }}
          </td>
          <td>
            {{ thesis.professor }}
          </td>
          <td>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="{{ thesis.progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ thesis.progress }}%;">
                {{ thesis.progress }}%
              </div>
            </div>
          </td>
          <td>
            <span>{{ thesis.last_change_date|date:'d.m.Y' }}</span>
          </td>
          <td>
            <span>&nbsp;</span>
          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

core/templates/group/view.html
{% extends 'page/base.html' %}

{% block title %} {{ object.name }} {% endblock %}

{% block breadcrumbs %}
<nav role="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb">
        <li class="active">{{ object.name }}</li>
    </ol>
  </div>
</nav>
{% endblock %}


{% block content %}
  <h1 class="page-header">{{ object.name }}</h1> <a href="{% url 'export:group' object.id %}">Экспорт в Excel</a>
  <div class="group-view">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#attendance" aria-controls="attendance" role="tab" data-toggle="tab">Посещаемость</a></li>
      <li role="presentation"><a href="#progress" aria-controls="progress" role="tab" data-toggle="tab">Успеваемость</a></li>
      <li role="presentation"><a href="#coursework" aria-controls="coursework" role="tab" data-toggle="tab">Курсовые работы</a></li>
      <li role="presentation"><a href="#graduatework" aria-controls="graduatework" role="tab"{% if final_thesis_data %} data-toggle="tab"{% else %} class="inactive" {% endif %}>Дипломные работы</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <!-- TAB ATTENDANCE -->
      <div role="tabpanel" class="tab-pane active" id="attendance">
        {% include 'group/attendance.html' %}
      </div>
      <!-- TAB PROGRESS -->
      <div role="tabpanel" class="tab-pane" id="progress">
        {% include 'group/progress.html' %}
      </div>
      <!-- TAB COURSEWORK -->
      <div role="tabpanel" class="tab-pane" id="coursework">
        {% include 'group/thesis.html' %}
      </div>
      <!-- TAB GRADUATEEWORK -->
      <div role="tabpanel" class="tab-pane" id="graduatework">
        {% include 'group/final_thesis.html' %}
      </div>
    </div>
  </div>
  <script>
  (function(){
    var self = this;

    $.fn.datepicker.dates['ru'] = {
        days: ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"],
        daysShort: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
        daysMin: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
        months: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
        monthsShort: ["Янв", "Фев", "Март", "Апр", "Май", "Ин", "Ил", "Авг", "Снт", "Окт", "Ноя", "Дек"],
        today: "Сегодня",
        clear: "Сбросить",
        format: "dd/mm/yyyy",
        titleFormat: "MM yyyy",
        weekStart: 1
    }
    
    $(document).ready(function() {
      // Init attendance_table
      self.attendanceTable = new self.AttendanceTable({
        table: $('#attendance_table')
      });
      self.attendanceTable.initDatePicker('.date');
      self.attendanceTable.listenOnChangeDate();
      // ----------------------------------

      // Init progress_table
      self.progressTable = new self.Table({
        table: $('#progress_table')
      });
      // ----------------------------------

      // Init coursework_table
      self.courseworkTable = new self.WorkTable({
        table: $('#coursework_table')
      });
      // ----------------------------------

      // Init coursework_table
      self.graduateworkTable = new self.WorkTable({
        table: $('#graduatework_table')
      });
      // ----------------------------------
    })
  })(this)

  </script>
{% endblock %}